### ISSUE TITLE
y'(t) syntax

### ISSUE THREAD

**Issue by runjaj** [jverzani/SymPyCore.jl#46]
In previous versions of SymPy.jl was possible to write an ODE as:

```
y''(t) + 3y'(t) +2y(t) ~ 1
```

I notice that this syntax isn't available now. Will it be restored in future versions? Just to know if I need to change my notes.

Thanks!

**Comment by jverzani** [comment]
Sorry, that syntax was deprecated and then removed. It required a special type for symbolic functions that wasn't necessary. In its place, there is `Differential` as a helper to make such formulas look a bit better that those in the `Python` docs which have `diff` all over them. This section of the docs illustrates: https://jverzani.github.io/SymPyCore.jl/dev/Tutorial/solvers/#Solving-Differential-Equations

**Comment by runjaj** [comment]
OK. I’ll change my notes.
