### ISSUE TITLE
Unexpected Result of Sym instead of SymFunction

### ISSUE THREAD

**Issue by tomaklutfu** [jverzani/SymPyCore.jl#53]
The constructors mentioned in this [line](https://github.com/jverzani/SymPyCore.jl/blob/05f6caddb4a3729b173c99a411bb312cb7fa91a2/src/types.jl#L69) return `Sym` objects instead of `SymFunction` but what is the use of them? The callabality is broken if `Sym` object is used since `f(t)`, then, returns the object `f` but silently it is changed to `t`. Then, it causes `diff(f(t), t)` to return 1.

**Comment by jverzani** [comment]
Yes, the issue is in calling `v(t)` for such objects. I need to catch that case. Thanks for letting me know.

**Comment by tomaklutfu** [comment]
Thanks for quick fix.
