### ISSUE TITLE
ambiguous methods

### ISSUE THREAD

**Issue by nsajko** [jverzani/SymPyCore.jl#62]
# Describe the bug

Many of the methods defined in this package cause dispatch ambiguities

# To Reproduce

Steps to reproduce the behavior: `Test.detect_ambiguities(SymPyCore, recursive=true)`

# Expected behavior

There should be no ambiguous methods

# Additional context

FTR it's possible to use the Aqua.jl package in a test suite to check for ambiguities and other issues automatically, like this: `Aqua.test_all(SymPyCore)`

## Some examples:  `==`, `isless`, `<`

This package defines at least one method with no type constraint on one of the arguments. For these three functions this necessarily causes ambiguities. It's necessary to either constrain both arguments or just delete the methods.

**Comment by jverzani** [comment]
Thanks, I'll have a look. (Really appreciate your attention here)

**Comment by jverzani** [comment]
Thanks again. I just checked in some changes to allow Aqua to run cleanly.
